### ISSUE TITLE
Game won't connect using Join Game button

### ISSUE THREAD

**Issue by MallocByte** [OnlineTicTacToe/onlinetictactoe.github.io#16]
When I use the enter game box it just stays on the main screen and doesn't go to the board so I cant join a game that a friend started. I can't even enter the link in the address bar.

**Comment by DusterTheFirst** [comment]
we need more details, please provide system info and steps to reproduce the problem

**Comment by mcrocks999** [comment]
Reproduced on Firefox Nightly, Windows 10.
[See here.](https://streamable.com/2r8l4)
EDIT: I realize I didn't include nickname, but it still dosen't work via join button even if nickname is entered.

**Comment by ghost** [comment]
Reproduced on Chrome Beta 62, Windows 10
This is definitely a bug with the **Join Game** button

**Comment by DusterTheFirst** [comment]
possibly fixed with latest commit: 50817090b9ba232d6a61f38978acd5c3d1ba3961

**Comment by ghost** [comment]
Yes, fixed by 50817090b9ba232d6a61f38978acd5c3d1ba3961

**Comment by DusterTheFirst** [comment]
i also fixed a bug with leaving the game
