### ISSUE TITLE
Able to place piece after player leaves game

### ISSUE THREAD

**Issue by ghost** [OnlineTicTacToe/onlinetictactoe.github.io#9]
Will provide more details once I'm home

**Comment by DusterTheFirst** [comment]
This might be from the server not resetting the game state to setup

**Comment by BoomerBoxer** [comment]
yes

**Comment by ghost** [comment]
I think it's actually because of the fact that the piece is rendered before the socket command is even sent to the server
The server may not send a turn variable, which causes the game to still think that it's your turn
